name: pangle_flutter
description: A Flutter plugin that supports ByteDance Pangle SDK on Android and iOS. Such as Splash Ads, Rewarded Video Ads, etc.
homepage: https://github.com/nullptrx/pangle_flutter
repository: https://github.com/nullptrx/pangle_flutter
issue_tracker: https://github.com/nullptrx/pangle_flutter/issues
version: 2.0.2

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.nullptrx.pangleflutter
        pluginClass: PangleFlutterPlugin
      ios:
        pluginClass: PangleFlutterPlugin

